### PR TITLE
Update data.json

### PR DESCRIPTION
**Pull request by UntouchedOdin0**
Remove toxic community and users

### CODE REVIEW

**Comment by MiniDigger** [comment]
yeah, thats a no from me

**Comment by Chew** [comment]
I feel taking out the "toxic community and users" takes away from the whole point of the generator. Aren't they the most likely to cause supposed drama?

**Comment by MiniDigger** [comment]
clip also is hardly toxic.

**Comment by mdcfe** [comment]
This defeats the point of the site, and breaks considerable existing permalinks.

**Pull request closed without merging**
