### PR TITLE
added a thing <3

### PR DESCRIPTION
**Pull request by Laarryy**

### CODE REVIEW

**Comment by Laarryy** [comment]
bUmP PlEaSe MeRgE ThIs PleAse

**Comment by zml2008** [comment]
fix the conflicts :(

**Comment by Laarryy** [comment]
dearest @zml2008 it appears that the royal GH said no https://i.imgur.com/Uk2wv4T.png

**Comment by zml2008** [comment]
`git rebase` tho?

**Comment by Laarryy** [comment]
it seems that Vic was added in my absence, thankfully

**Pull request closed without merging**
